### ISSUE TITLE
mjj大佬能不能在readme里面写个部署到tx无服务器云函数的教程啊

### ISSUE THREAD

**Issue by liby** [qkqpttgf/hostloccredit#1]
![demo](https://user-images.githubusercontent.com/38807139/60405734-bef3ac80-9be4-11e9-9dc8-1b721cc89d28.png)
- 类似这样.运行环境,执行方法,函数配置什么的

**Comment by qkqpttgf** [comment]
他那个是python，我这个是shell，SCF不支持的。
